POST http://localhost:3000/api/rentals
Content-Type: application/json

{
  "userId": "690e5638312cfa18d23eb950",
  "carId": 2,
  "startDate": "03/04/2004",
  "endDate": "06/04/2004"
}
###
GET http://localhost:3000/api/rentals
###
DELETE http://localhost:3000/api/rentals/7
###
PATCH http://localhost:3000/api/rentals/8
Content-Type: application/json

{
  "startDate": "05/04/2004",
  "endDate": "10/04/2004"
}