POST http://localhost:3000/api/rentals
Content-Type: application/json

{
  "userId": "6916bd964324ff58d937a115",
  "carId": 4,
  "startDate": "03/04/2004",
  "endDate": "06/04/2004"
}
###
GET http://localhost:3000/api/rentals
###
DELETE http://localhost:3000/api/rentals/7
###
PATCH http://localhost:3000/api/rentals/8
Content-Type: application/json

{
  "startDate": "05/04/2004",
  "endDate": "10/04/2004"
}