POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "secure1234"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTQxZmJmOGY5NzhhNDM2NTI4YjYzMiIsImlhdCI6MTc1NTgzMDczNSwiZXhwIjoxNzU1ODM0MzM1fQ.lNmmDdEUtax_U5s0npBPLfr4DVxtuNk1eAWlp_f-jjI